# Используем официальный Python образ
FROM python:3.12-slim

# Устанавливаем зависимости системы (может понадобиться для torch/transformers)
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем зависимости Python
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

RUN pip install hf_xet
# Копируем все файлы проекта
COPY . .

# Открываем порт
EXPOSE 8000

# Запускаем FastAPI-сервер
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]