spring:
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
jwt:
  secret: apppapdfsdlflksajgllhfjghdklfjhdfshhfghdjghfdjgfcdfdtrfdshfgshgsdgfdhsfdsredsretfdcxgfhdsfhgsdh
  lifetime: 180m