ai:
  service:
    url: ${AI_URL:http://localhost:8000}

spring:
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 120000
      initialization-fail-timeout: 180000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: ${MONGO_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: techtrackinvest@gmail.com
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  secret: apppapdfsdlflksajgllhfjghdklfjhdfshhfghdjghfdjgfcdfdtrfdshfgshgsdgfdhsfdsredsretfdcxgfhdsfhgsdh
  lifetime: 180m

# CORS Configuration
cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

server:
  address: 0.0.0.0
  port: 8080


