spring:
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: ${MONGO_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: techtrackinvest@gmail.com
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  secret: apppapdfsdlflksajgllhfjghdklfjhdfshhfghdjghfdjgfcdfdtrfdshfgshgsdgfdhsfdsredsretfdcxgfhdsfhgsdh
  lifetime: 180m