name: TechTrackInvest CI
on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'backend/src/**'
      - '.github/workflows/build.yaml'
  push:
    branches: [ "dev" ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yaml'
jobs:
  build-and-test:
   runs-on: ubuntu-latest
   
   services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
   steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Create .env file for DB connection
      run: |
        echo "DB_URL=jdbc:postgresql://localhost:5432/testdb" > .env
        echo "DB_USERNAME=testuser" > .env
        echo "DB_PASSWORD=testpass" > .env

    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          nc -z localhost 5432 && exit 0
          sleep 5
        done
        exit 1
        
    - name: Build and test
      run: mvn -B verify
    - name: publish Test Report
      if: always()  
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '**/surefire-reports/TEST-*.xml'

    - name: Cleanup
      run: rm -f .env
