name: TechTrackInvest CI
on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'backend/src/**'
      - '.github/workflows/build.yaml'
  push:
    branches: [ "dev" ]
    paths:
      - 'backend/src/**'
      - '.github/workflows/build.yaml'
jobs:
  build-and-test:
   runs-on: ubuntu-latest
   permissions:
      checks: write
      pull-requests: write
      contents: read
   defaults:
     run:
       working-directory: ./backend 
   
  
  
   steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

          
    - name: Build and test
      run: mvn -B verify
      
    - name: publish Test Report
      if: always()  
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: '**/surefire-reports/TEST-*.xml'
        include_passed: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cleanup
      run: rm -f .env
