name: Deploy to vps

on:
  push:
    branches:
      - release

permissions:
  packages: write

jobs:
  build_and_push_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Check gh hash before pushing to registry
        run: |
          echo ${{ github.sha }}

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/
          push: true
          tags: |
            ghcr.io/patersss/tecktrackinvestbackend:latest
            ghcr.io/patersss/tecktrackinvestbackend:${{ github.sha }}
  
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Check gh hash before pushing to registry
        run: |
          echo ${{ github.sha }}
      
      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front/
          push: true
          build-args: |
            REACT_APP_API_URL=http://176.98.178.227:8080
          tags: |
            ghcr.io/patersss/tecktrackinvestfrontend:latest
            ghcr.io/patersss/tecktrackinvestfrontend:${{ github.sha }}

  deploy_game:
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend
      - build_and_push_frontend
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: check commit sha
      run: |
        echo ${{ github.sha }}

    - name: create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
        echo "CORS_ALLOWED_ORIGINS=http://176.98.178.227" >> ./envfile
    
    - name: Check gh hash after pushing to registry
      run: |
        echo ${{ github.sha }}
    
    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: game
        file: docker-stack.yaml
        host: 176.98.178.227
        user: ${{ secrets.VPS_USER }}
        ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
        env_file: ./envfile
        registry_auth: true
        registry_host: "ghcr.io"
        registry_user: ${{ github.DEPLOY_USER }}
        registry_pass: ${{ secrets.GH_TOKEN }}
    