name: Deploy to vps

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            git pull origin release

            echo "CORS_ALLOWED_ORIGINS=http://176.98.178.227" > .env
            echo "REACT_APP_API_URL=http://176.98.178.227:8080" >> .env
            docker compose down
            docker compose up -d --build
